# .github/workflows/publish.yml

name: Publish

on:
  push:
    branches:
      - ${MAIN_BRANCH}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allows reading of the repository's contents.
      id-token: write # Allows the creation of an ID token for authentication with JSR.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to JSR
        run: npx jsr publish
